# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c9b885ea3138dbce62e8bdf1153895e7dc00286e9c3a530f049d8295428d5c43282fd48c9d90ff6781fb172213e05f0eca6b6eaa63a5a283aa3b6abf723aef5

test:
  secret_key_base: 20d0631ef505593ac8eef04ad27585fe7920765e66a370d9d1823bda3dcadc30cf248ed3dfdf3d59088dd29a5d036289a4a7aab290ee06cccee3bcf9bdfc0f33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
